### ISSUE TITLE
Add documentation describing how to create a Calipers plugin

### ISSUE THREAD

**Issue by mgartner** [calipersjs/calipers#45]

**Comment by borodean** [comment]
PostCSS has a plugin boilerplate: https://github.com/postcss/postcss-plugin-boilerplate

**Comment by borodean** [comment]
Stylelint has a test helper for rule developers: https://github.com/stylelint/stylelint-rule-tester

**Comment by mgartner** [comment]
@borodean thanks for the resources. For now I've put an example in the README. If you think more is necessary, just let me know.

I think closing this is the last piece of v2 and the new plugin system. I've published all the plugins to NPM. Let me know if I forgot anything. Thanks so much for the great idea and all the help in getting this done @borodean! :beers:

**Comment by borodean** [comment]
@mgartner nice job! I was off for a few days and was surprised to see everything's done when I've got back.

Now I'm going to see how it works in production :-)
