### ISSUE TITLE
can not install pdf plugin on mac node 6.x and 8.x

### ISSUE THREAD

**Issue by Pana** [calipersjs/calipers#61]
<img width="1013" alt="screen shot 2017-09-09 at 14 23 58" src="https://user-images.githubusercontent.com/552081/30237730-b2977ba0-94fd-11e7-8089-03fe4fc38aed.png">

**Comment by Pana** [comment]
This is because poppler-simle need install 
```
yum install poppler
yum install poppler-cpp-devel.x86_64
```

**Comment by mgartner** [comment]
The requirement for poppler and its development C++ interface is mentioned in the README. It is only required if you use the PDF plugin.

It sounds like you resolved the issue. I'm going to close this for now, but if you are still having issues, go ahead and re-open an issue.
