### ISSUE TITLE
Incorrect size for SVG with stroke-width on root element

### ISSUE THREAD

**Issue by ashsearle** [calipersjs/calipers#63]
Given an SVG like:
`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 60" stroke-width="2">`

The `stroke-width` is picked up as a `width` (and then used to calculate `height`.)  The result being `{ width: 2, height: 1 }` instead of the expected `{ width: 100, height: 60 }` specified in `viewBox`.

I've create a PR to fix it: calipersjs/calipers-svg#1

**Comment by mgartner** [comment]
Thanks for the report and fix! calipers-svg@2.0.1 has been published with your fix included: https://www.npmjs.com/package/calipers-svg
