### ISSUE TITLE
GlobalParams.h no such file or directory 

### ISSUE THREAD

**Issue by LandyCuadra** [calipersjs/calipers#73]
during this installation of poppler-pdf, I get this error, already installed the dependency mentioned in the documentation, It is something I am missing?

npm ERR! code 1
npm ERR! path /home/landyx/Ralop Technologies/microservicios/botUtilities/node_modules/poppler-simple
npm ERR! command failed
npm ERR! command sh -c (node-gyp rebuild) || (exit 1)
npm ERR! make: Entering directory '/home/landyx/Ralop Technologies/microservicios/botUtilities/node_modules/poppler-simple/build'
npm ERR!   CXX(target) Release/obj.target/poppler/src/poppler.o
npm ERR! make: Leaving directory '/home/landyx/Ralop Technologies/microservicios/botUtilities/node_modules/poppler-simple/build'
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@15.14.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.7.3 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/landyx/Ralop Technologies/microservicios/botUtilities/node_modules/poppler-simple/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/landyx/.cache/node-gyp/15.14.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/landyx/.cache/node-gyp/15.14.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/landyx/.cache/node-gyp/15.14.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/landyx/Ralop Technologies/microservicios/botUtilities/node_modules/poppler-simple',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! In file included from ../src/poppler.cc:3:
npm ERR! ../src/NodePopplerDocument.h:4:10: fatal error: GlobalParams.h: No such file or directory
npm ERR!  #include <GlobalParams.h>
npm ERR!           ^~~~~~~~~~~~~~~~
npm ERR! compilation terminated.
npm ERR! make: *** [poppler.target.mk:123: Release/obj.target/poppler/src/poppler.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:369:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Linux 4.19.0-16-amd64
npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /home/landyx/Ralop Technologies/microservicios/botUtilities/node_modules/poppler-simple
npm ERR! gyp ERR! node -v v15.14.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/landyx/.npm/_logs/2021-06-03T16_21_22_820Z-debug.log

**Comment by mbernwieser** [comment]
For me `libpoppler-private-dev` was missing: https://github.com/blackbeam/poppler-simple#ubuntu

**Comment by Thexumaker** [comment]
Hi, Sorry for the very late update here but yes @mbernwieser is correct in that you are likely missing `libpoppler-private-dev`

Will be updating the readme ASAP
