### ISSUE TITLE
Problems after calipers jpeg update

### ISSUE THREAD

**Issue by s1de21** [calipersjs/calipers#90]
Hey,

after the calipers 2.1 update many running grunt systems are failing cause 

https://www.npmjs.com/package/assets

is using it. 

You might consider your changes as major release.

sincerely

LVR

**Comment by s1de21** [comment]
Affects the png package as well.

**Comment by Thexumaker** [comment]
Will be taking a look.

**Comment by Thexumaker** [comment]
@s1de21 is there a bit more context on the issue or specific errors you're seeing? I checked with the assets repo and all the tests are still passing with the latest version. Also checked https://www.npmjs.com/package/grunt, and I'm not actually seeing calipers as a dependency.

**Comment by Thexumaker** [comment]
@adrianfalleiro I no longer have access to publish/unpublish npm versions. Regardless of how this plays out it may be smarter to just unpublish all the changes in these repos and do major version upgrades? Thoughts

**Comment by adrianfalleiro** [comment]
@s1de21 @Thexumaker Republished the changes as `3.0.0` and deprecated `2.1.0`.
